# -*- coding: utf-8 -*-
"""Text-to-image generation using Stable diffusion and diffusers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnrNYTu33_lx72WTNV0s_Q1fQUUQ64O2

Text-to-image generation using Stable diffusion and diffusers
---



---
"""

!pip install diffusers transformers accelerate

from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt
import torch

model_id1="dreamlike-art/dreamlike-diffusion-1.0"
model_id2="stabilityai/stable-diffusion-x1-base-1.0"

pipe=StableDiffusionPipeline.from_pretrained(model_id1,torch_dtype=torch.float,use_safetensors=True)
pipe=pipe.to("cuda")

prompt="A majestic and divine depiction of Lord Ganesha, the elephant-headed Hindu deity, sitting gracefully on a lotus flower. He is adorned with golden jewelry and a traditional silk dhoti, holding a modak (sweet) in one hand, a lotus in another, an axe in the third, and blessing with the fourth. The background is ethereal, with soft glowing light, floating petals, and a serene sky with warm golden hues. Highly detailed, vibrant colors, spiritual and majestic atmosphere, realistic yet divine illustration, cinematic lighting."

image=pipe(prompt).images[0]

image

prompt2="A girl is sitting on a chair & she is accompanied by her tiger.Make sure to keep it cinematic and color to be golden iris"

image2=pipe(prompt2).images[0]
image2